### ISSUE TITLE
Add logo.svg?

### ISSUE THREAD

**Issue by kirbyfan64** [vuejs/art#1]
It's the only Illustrator file that doesn't have a .svg counterpart...

**Comment by limichange** [comment]
[logo.svg.zip](https://github.com/vuejs/art/files/1253589/logo.svg.zip)

**Comment by limichange** [comment]
https://raw.githubusercontent.com/limichange/art/master/logo.svg

**Comment by yyx990803** [comment]
Thanks @limichange for #2 !

**Comment by kirbyfan64** [comment]
Thanks!
